function pretty_plot(obj)
% Makes the BrainSpace plots prettier inside live scripts.
obj.handles.figure.Units = 'pixels';
set(obj.handles.axes, 'Units', 'pixels')
set(obj.handles.colorbar, 'Units', 'pixels');
obj.handles.figure.Position = [1, 1, 800, size(obj.data, 2) * 95*3];
set(obj.handles.text, 'FontSize', 20);
for jj = 1:size(obj.data, 2) % variates
    obj.handles.colorbar(jj).Position = [...
        720, ...
        30 + (size(obj.data, 2) * 95*3) - 10 - jj*90*3, ...
        12, ...
        100];
    for ii = 1:2 % views
        obj.handles.axes(jj, ii).Position = [...
            75 + (ii-1)*105*3, ...
            (size(obj.data, 2) * 95*3) - jj*95*3, ...
            300, ...
            300];
    end
end
end